### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by mattiasduerrmeier** [shiroininjaTech/AstroNinja-Alpha#1]
This repository doesn't have license at the moment. 
I think it would be a good idea to add a license to your program before users install it.

I will gladly help you with it if you know under which license you want this repository to be.

**Comment by shiroininjaTech** [comment]
Which one do you suggest? Thanks.

**Comment by tiagoFlach** [comment]
MIT

https://choosealicense.com/

**Comment by shiroininjaTech** [comment]
Thank you, added it

**Comment by mattiasduerrmeier** [comment]
I would suggest the GPLv3.

**Comment by shiroininjaTech** [comment]
I'm leaning more toward the GPL, it seems more restrictive. While I want my project to be open sourced, I'm also paranoid about somebody completely taking something I've put a lot of effort into, and using it for commercial gain, which isn't what I want for it.

**Comment by mattiasduerrmeier** [comment]
The GPLv3 still let's someone use the source code form commercial purposes. However, the software made by a company using this software has to be under the GPLv3 too.

You can learn more about the GPLv3 here : https://www.gnu.org/licenses/quick-guide-gplv3.html
The https://choosealicense.com website is also a great tool.

**Comment by shiroininjaTech** [comment]
Thank you, it’s been approved and merged. I was leaning towards the gpl as well
