### ISSUE TITLE
Don't know how to remove White Space and scroll bar in the SpaceX video object

### ISSUE THREAD

**Issue by shiroininjaTech** [shiroininjaTech/AstroNinja-Alpha#10]
I've been working on trying to remove the white space and scroll bar that appears in the web object that contains the Space X launch videos that appeared when I switched to scraping videos directly from spacex.com. It now uses an html frame embed instead of just a URL that is scraped.

**Comment by hernandez87v** [comment]
Hey so I have the second scroll bar removed but how would I go about adding a different URL in the code to test that it will still work? I was trying to look in the spaceXlaunch.py but not sure. If that is the right spot I can do more digging. 

Also by whitespace did you want something in its place or the whole container collapsed to just show "SpaceX Lens  |  Starlink Mission" ?

**Comment by shiroininjaTech** [comment]
Hey, first off, thank you for taking the time to look at the project and in advance for helping out.

What you could do is in this section of spaceXlaunch.py  is change the string in  link[0] to any url string, like this:


    # Turning the link into an embed link.
    global fixedLink
    fixedLink = link[0].replace('https://youtu.be/', 'https://www.youtube.com/embed/')
    link[0] = "www.google.com"  #or whatever  url you want to try.

**Comment by shiroininjaTech** [comment]
Issue has been solved with the pull request from hernandez87v and fixes with the iframe object. Thanks again man.
