### ISSUE TITLE
Installation: Test non debian-based distributions

### ISSUE THREAD

**Issue by mattiasduerrmeier** [shiroininjaTech/AstroNinja-Alpha#4]
I believe that installation instructions should work on other GNU/Linux distributions (non Debian-based) as well. 
I will give it a try on other distributions and change the installation instructions afterwards.

On a side note, I see on your profile that you have 2 AstroNinja repositories: AstroNinja, & AstroNinja-Alpha. 

Are you keep the first as a way to test your software before pushing it to the main branch of this repository?
If so, I can help you with that. By making a new branch on this repository, you can have a release branch (main branch) and a test branch. You can also have many other branches if needed, depending if you need them.

I would recommend that you only keep one, to make it clear which one is the one to use. 
Hopefully this will help you.

**Comment by shiroininjaTech** [comment]
The main issue I had on other distributions was in arch distros, they use different package managers and some packages are named differently. I’m having trouble getting it to launch in manjaro for instance. 

I am using the other repo as a kind of backup, while this repo is the newest version.

Thank you for your help

**Comment by shiroininjaTech** [comment]
How would I make a test branch?

**Comment by mattiasduerrmeier** [comment]
I believe this link should help you. I prefer to link you the help page instead, because I must say that I'm not very familiar with GitHub & Git too. 

Link: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-branches

**Comment by shiroininjaTech** [comment]
Thank you. This is really my first time collaborating on github. I've only really posted things on here to link in a resume. I'll check out the link. I appreciate the help you've given towards the project.

**Comment by mattiasduerrmeier** [comment]
I am fairly new to collaborating on GitHub as well. This project might be a good opportunity to learn more about GitHub!
I like to idea of you project and think it's really cool, so I will gladly help you!

**Comment by shiroininjaTech** [comment]
Thank you for your interest in the project. I'm really enjoying collaborating. 

I haven't tried running on Void Linux yet, I honestly forgot about it. I've only tried Ubuntu, Linux Mint, Debian, and Manjaro. Manjaro I haven't gotten working, but the rest worked. I assume its a dependency issue as well, or what package manager does void use? I've only written the install.sh to use apt, but we may need to add whatever package manager void uses. 

I will try to work on automating more of the installation either tonight or tomorrow. Some of it is going to be easy and I can't believe I didn't think of it until you said it, lol.

**Comment by shiroininjaTech** [comment]
I also added moved a couple of the instructions in the readme to be performed by the install script, as well as tried to make the instructions more clear.
