### ISSUE TITLE
Ubuntu 20.04 Execution error

### ISSUE THREAD

**Issue by infinitymakerspace** [shiroininjaTech/AstroNinja-Alpha#6]
Hi guys, installation went fine, but executing from icon hangs with no display and from command line it gives the errors found in screen grab below. 
![astroninja_error](https://user-images.githubusercontent.com/61062911/85956151-3b4dd680-b984-11ea-8af2-e63e22c215ca.png)

**Comment by shiroininjaTech** [comment]
Which install script did you use? And could you see if it installed scrapy correctly? Because this is a new issue

**Comment by infinitymakerspace** [comment]
Hi there

I ran ./install.sh its on Ubuntu 20.04

**Comment by shiroininjaTech** [comment]
Ok, thank you for letting me know, I’ll try it out tomorrow on a fresh install of 20.04 in vm tomorrow.

**Comment by infinitymakerspace** [comment]
Many Thanks Buddy :-)

**Comment by shiroininjaTech** [comment]
I’m hoping it’s just some dumb issue I introduced in an update recently or something. I don’t know why it’s not finding scrapy unless the script didn’t install it.

**Comment by infinitymakerspace** [comment]
Its all good, its part of testing :-)

**Comment by shiroininjaTech** [comment]
Ok, so I just tested it on a fresh install of Ubuntu 20.04 and reinstalled it in Linux Mint and has worked in both. I have two questions to ask: 
Could you try running python3 AstroNinjaMain.py in the .AstroNinja/ folder the script installs it to?
and if that doesn't work,
could you try re-running the install script and sending me screenshots of what displays in the terminal during the process, to see if it's throwing some kind of error when trying to run the pip3 command to install scrapy?

**Comment by infinitymakerspace** [comment]
Hi there

I did use python3 in the command plus that is the only python
environment on my install.  I will do a clean clone and run the script and
see what happens and give feedback.  Need to boot into my Ubuntu partition
as I need to capture Micro Python flashing methods for ESP8266 :-)

**Comment by shiroininjaTech** [comment]
It’s sounding like the install script didn’t work right on your system  for some reason.  It should have installed the AstroNinja files to a .AstroNinja/ folder in your home directory, which will make it a hidden folder, which you might not see in the file explorer without using ctrl+h. Or the command ls -a in terminal.

**Comment by infinitymakerspace** [comment]
Scrapy was not installed ran pip install scrapy, currently getting a
Segmentation fault (core dumped).  I am going to look to see if I can find
the hidden folder and then re-clone a clean copy and re-run the install
script.

**Comment by infinitymakerspace** [comment]
[image: astroninja.png]

going to cleanup and re-do clone and install

**Comment by infinitymakerspace** [comment]
> It’s sounding like the install script didn’t work right on your system for some reason. It should have installed the AstroNinja files to a .AstroNinja/ folder in your home directory, which will make it a hidden folder, which you might not see in the file explorer without using ctrl+h. Or the command ls -a in terminal.

(base) gert@luminary99:~/.AstroNinja$ python AstroNinjaMain.py 
QLayout: Attempting to add QLayout "" to App "", which already has a layout
QLayout: Attempting to add QLayout "" to App "", which already has a layout
AstroNinjaMain.py:863: DeprecationWarning: AppURLopener style of invoking requests is deprecated. Use newer urlopen functions/methods
  opener = AppURLopener()
QLayout: Attempting to add QLayout "" to App "", which already has a layout
Segmentation fault (core dumped)
(base) gert@luminary99:~/.AstroNinja$

**Comment by shiroininjaTech** [comment]
Up to the segment fault, most of that is normal, it typically hangs a bit on the last layout message while it processes, but it eventually loads. I wonder what could be causing the fault.

**Comment by infinitymakerspace** [comment]
Same error... weird

**Comment by shiroininjaTech** [comment]
Today I've had trouble getting the part of the app that scrapes SpaceX videos from YouTube to connect to the site. I don't know if that's related or not. It seems their servers seem a bit slow to respond. We'll have to follow up in the future because I've become obsessed with finding a solution. haha.

**Comment by infinitymakerspace** [comment]
Issue was resolved, Anaconda python distribution does not require the command to be formatted as pip3 install shironinjaTech was notified via PM

**Comment by shiroininjaTech** [comment]
Thank you
