### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by infinitymakerspace** [shiroininjaTech/AstroNinja-Alpha#8]
Hi guys 

This is from my Ubuntu setup after updating to new AstronNinjaMain.py

(base) gert@luminary99:~/.AstroNinja$ python3 AstroNinjaMain.py 
  File "AstroNinjaMain.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by shiroininjaTech** [comment]
Weird. I’ll check out the beginning of the file.

**Comment by infinitymakerspace** [comment]
Copy That!

Many Thanks

**Comment by shiroininjaTech** [comment]
did you copy and paste the file? maybe github's formatting messed it up? I haven't gotten that issue with a fresh clone. But who knows, github is still uncharted waters for me

**Comment by infinitymakerspace** [comment]
I will do a fresh clone :-)

**Comment by shiroininjaTech** [comment]
I'm closing the issue, since it has been unrepeatable with fresh clones.

**Comment by infinitymakerspace** [comment]
Cool :-)
